### ISSUE TITLE
Trained Model

### ISSUE THREAD

**Issue by dharakotecha** [drc10723/bert_quora_question_pairs#1]
Can you please provide the trained model along with the usage details?
I would like to apply it in my project which has questions which are similar to that of quora question pairs dataset and hence I would like to use the trained model. I am new to BERT so please provide usage details as well. Thanks !

**Comment by dharmendrach** [comment]
You can run the colab notebook given in this repo and will get trained model in output directory. Also checkpoint can be found at [this link](https://drive.google.com/open?id=14L8dPI5hdTEYqvUS-_yCA7wy_ey92Fxt). For usage please once go through the notebook, You can use this checkpoint as init checkpoint and skip training.
